// Copyright Lifelike & Believable. All Rights Reserved.

// Generated by Build/Scripts/sync_o3ds_core.py from src/ and Build/o3ds-core-manifest.txt; do not edit.
// Compiles src/o3ds/stream_writer.cpp from the mirror in Source/ThirdParty/Open3DStreamCore
// (docs/adr/0003-core-library-delivery-to-plugin.md).

#include "O3DSCoreSourceBegin.h"
#include "o3ds/stream_writer.cpp"
#include "O3DSCoreSourceEnd.h"
