// Copyright Lifelike & Believable. All Rights Reserved.

#include "Modules/ModuleManager.h"

THIRD_PARTY_INCLUDES_START
#include "flatbuffers/base.h"
THIRD_PARTY_INCLUDES_END

// o3ds_generated.h in Source/ThirdParty/Open3DStreamCore was generated by flatc 2.0.6, and the
// FlatBuffers runtime headers next to it must be the same version (CORE-21). The sync script
// copies both from the thirdparty/flatbuffers pin; this catches a hand-edited mirror, or other
// FlatBuffers headers found first on the include path (docs/adr/0003).
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 && FLATBUFFERS_VERSION_MINOR == 0 && FLATBUFFERS_VERSION_REVISION == 6,
	"Open3DStreamCore expects the FlatBuffers 2.0.6 runtime headers that match o3ds_generated.h. "
	"Run Build/Scripts/sync_o3ds_core.py after changing the thirdparty/flatbuffers pin.");

/**
 * The Open3DStream core (src/o3ds) compiled from source. The module has no startup work: it only
 * holds the core's code, which the other modules call through O3DS_API (docs/adr/0003).
 */
class FOpen3DStreamCoreModule : public IModuleInterface
{
};

IMPLEMENT_MODULE(FOpen3DStreamCoreModule, Open3DStreamCore)
