// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_O3DS_O3DS_DATA_H_
#define FLATBUFFERS_GENERATED_O3DS_O3DS_DATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 2 &&
              FLATBUFFERS_VERSION_MINOR == 0 &&
              FLATBUFFERS_VERSION_REVISION == 8,
             "Non-compatible flatbuffers version included");

namespace O3DS {
namespace Data {

struct Matrix;

struct Translation;

struct Rotation;

struct Scale;

struct TranslationUpdate;

struct RotationUpdate;

struct ScaleUpdate;

struct Transform;
struct TransformBuilder;

struct Subject;
struct SubjectBuilder;

struct SubjectUpdate;
struct SubjectUpdateBuilder;

struct SubjectList;
struct SubjectListBuilder;

struct Curve;
struct CurveBuilder;

struct CurveUpdate;

enum Direction : int8_t {
  Direction_None = 0,
  Direction_Left = 1,
  Direction_Right = 2,
  Direction_Forward = 3,
  Direction_Back = 4,
  Direction_Up = 5,
  Direction_Down = 6,
  Direction_MIN = Direction_None,
  Direction_MAX = Direction_Down
};

inline const Direction (&EnumValuesDirection())[7] {
  static const Direction values[] = {
    Direction_None,
    Direction_Left,
    Direction_Right,
    Direction_Forward,
    Direction_Back,
    Direction_Up,
    Direction_Down
  };
  return values;
}

inline const char * const *EnumNamesDirection() {
  static const char * const names[8] = {
    "None",
    "Left",
    "Right",
    "Forward",
    "Back",
    "Up",
    "Down",
    nullptr
  };
  return names;
}

inline const char *EnumNameDirection(Direction e) {
  if (flatbuffers::IsOutRange(e, Direction_None, Direction_Down)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDirection()[index];
}

enum Component : int8_t {
  Component_Translation = 0,
  Component_Rotation = 1,
  Component_Scale = 2,
  Component_Matrix = 3,
  Component_MIN = Component_Translation,
  Component_MAX = Component_Matrix
};

inline const Component (&EnumValuesComponent())[4] {
  static const Component values[] = {
    Component_Translation,
    Component_Rotation,
    Component_Scale,
    Component_Matrix
  };
  return values;
}

inline const char * const *EnumNamesComponent() {
  static const char * const names[5] = {
    "Translation",
    "Rotation",
    "Scale",
    "Matrix",
    nullptr
  };
  return names;
}

inline const char *EnumNameComponent(Component e) {
  if (flatbuffers::IsOutRange(e, Component_Translation, Component_Matrix)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesComponent()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Matrix FLATBUFFERS_FINAL_CLASS {
 private:
  float m00_;
  float m01_;
  float m02_;
  float m03_;
  float m10_;
  float m11_;
  float m12_;
  float m13_;
  float m20_;
  float m21_;
  float m22_;
  float m23_;
  float m30_;
  float m31_;
  float m32_;
  float m33_;

 public:
  Matrix()
      : m00_(0),
        m01_(0),
        m02_(0),
        m03_(0),
        m10_(0),
        m11_(0),
        m12_(0),
        m13_(0),
        m20_(0),
        m21_(0),
        m22_(0),
        m23_(0),
        m30_(0),
        m31_(0),
        m32_(0),
        m33_(0) {
  }
  Matrix(float _m00, float _m01, float _m02, float _m03, float _m10, float _m11, float _m12, float _m13, float _m20, float _m21, float _m22, float _m23, float _m30, float _m31, float _m32, float _m33)
      : m00_(flatbuffers::EndianScalar(_m00)),
        m01_(flatbuffers::EndianScalar(_m01)),
        m02_(flatbuffers::EndianScalar(_m02)),
        m03_(flatbuffers::EndianScalar(_m03)),
        m10_(flatbuffers::EndianScalar(_m10)),
        m11_(flatbuffers::EndianScalar(_m11)),
        m12_(flatbuffers::EndianScalar(_m12)),
        m13_(flatbuffers::EndianScalar(_m13)),
        m20_(flatbuffers::EndianScalar(_m20)),
        m21_(flatbuffers::EndianScalar(_m21)),
        m22_(flatbuffers::EndianScalar(_m22)),
        m23_(flatbuffers::EndianScalar(_m23)),
        m30_(flatbuffers::EndianScalar(_m30)),
        m31_(flatbuffers::EndianScalar(_m31)),
        m32_(flatbuffers::EndianScalar(_m32)),
        m33_(flatbuffers::EndianScalar(_m33)) {
  }
  float m00() const {
    return flatbuffers::EndianScalar(m00_);
  }
  float m01() const {
    return flatbuffers::EndianScalar(m01_);
  }
  float m02() const {
    return flatbuffers::EndianScalar(m02_);
  }
  float m03() const {
    return flatbuffers::EndianScalar(m03_);
  }
  float m10() const {
    return flatbuffers::EndianScalar(m10_);
  }
  float m11() const {
    return flatbuffers::EndianScalar(m11_);
  }
  float m12() const {
    return flatbuffers::EndianScalar(m12_);
  }
  float m13() const {
    return flatbuffers::EndianScalar(m13_);
  }
  float m20() const {
    return flatbuffers::EndianScalar(m20_);
  }
  float m21() const {
    return flatbuffers::EndianScalar(m21_);
  }
  float m22() const {
    return flatbuffers::EndianScalar(m22_);
  }
  float m23() const {
    return flatbuffers::EndianScalar(m23_);
  }
  float m30() const {
    return flatbuffers::EndianScalar(m30_);
  }
  float m31() const {
    return flatbuffers::EndianScalar(m31_);
  }
  float m32() const {
    return flatbuffers::EndianScalar(m32_);
  }
  float m33() const {
    return flatbuffers::EndianScalar(m33_);
  }
};
FLATBUFFERS_STRUCT_END(Matrix, 64);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Translation FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Translation()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Translation(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Translation, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Rotation FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Rotation()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Rotation(float _x, float _y, float _z, float _w)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        w_(flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Rotation, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Scale FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Scale()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Scale(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Scale, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) TranslationUpdate FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  int32_t i_;

 public:
  TranslationUpdate()
      : x_(0),
        y_(0),
        z_(0),
        i_(0) {
  }
  TranslationUpdate(float _x, float _y, float _z, int32_t _i)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        i_(flatbuffers::EndianScalar(_i)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  int32_t i() const {
    return flatbuffers::EndianScalar(i_);
  }
};
FLATBUFFERS_STRUCT_END(TranslationUpdate, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) RotationUpdate FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;
  int32_t i_;

 public:
  RotationUpdate()
      : x_(0),
        y_(0),
        z_(0),
        w_(0),
        i_(0) {
  }
  RotationUpdate(float _x, float _y, float _z, float _w, int32_t _i)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        w_(flatbuffers::EndianScalar(_w)),
        i_(flatbuffers::EndianScalar(_i)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return flatbuffers::EndianScalar(w_);
  }
  int32_t i() const {
    return flatbuffers::EndianScalar(i_);
  }
};
FLATBUFFERS_STRUCT_END(RotationUpdate, 20);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) ScaleUpdate FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  int32_t i_;

 public:
  ScaleUpdate()
      : x_(0),
        y_(0),
        z_(0),
        i_(0) {
  }
  ScaleUpdate(float _x, float _y, float _z, int32_t _i)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        i_(flatbuffers::EndianScalar(_i)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  int32_t i() const {
    return flatbuffers::EndianScalar(i_);
  }
};
FLATBUFFERS_STRUCT_END(ScaleUpdate, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) CurveUpdate FLATBUFFERS_FINAL_CLASS {
 private:
  float value_;
  int32_t i_;

 public:
  CurveUpdate()
      : value_(0),
        i_(0) {
  }
  CurveUpdate(float _value, int32_t _i)
      : value_(flatbuffers::EndianScalar(_value)),
        i_(flatbuffers::EndianScalar(_i)) {
  }
  float value() const {
    return flatbuffers::EndianScalar(value_);
  }
  int32_t i() const {
    return flatbuffers::EndianScalar(i_);
  }
};
FLATBUFFERS_STRUCT_END(CurveUpdate, 8);

struct Transform FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TransformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARENT = 4,
    VT_NAME = 6,
    VT_TRANSLATION = 8,
    VT_ROTATION = 10,
    VT_SCALE = 12,
    VT_MATRIX = 14,
    VT_COMPONENTS = 16
  };
  int32_t parent() const {
    return GetField<int32_t>(VT_PARENT, 0);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const O3DS::Data::Translation *translation() const {
    return GetStruct<const O3DS::Data::Translation *>(VT_TRANSLATION);
  }
  const O3DS::Data::Rotation *rotation() const {
    return GetStruct<const O3DS::Data::Rotation *>(VT_ROTATION);
  }
  const O3DS::Data::Scale *scale() const {
    return GetStruct<const O3DS::Data::Scale *>(VT_SCALE);
  }
  const flatbuffers::Vector<const O3DS::Data::Matrix *> *matrix() const {
    return GetPointer<const flatbuffers::Vector<const O3DS::Data::Matrix *> *>(VT_MATRIX);
  }
  const flatbuffers::Vector<int8_t> *components() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_COMPONENTS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PARENT, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<O3DS::Data::Translation>(verifier, VT_TRANSLATION, 4) &&
           VerifyField<O3DS::Data::Rotation>(verifier, VT_ROTATION, 4) &&
           VerifyField<O3DS::Data::Scale>(verifier, VT_SCALE, 4) &&
           VerifyOffset(verifier, VT_MATRIX) &&
           verifier.VerifyVector(matrix()) &&
           VerifyOffset(verifier, VT_COMPONENTS) &&
           verifier.VerifyVector(components()) &&
           verifier.EndTable();
  }
};

struct TransformBuilder {
  typedef Transform Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_parent(int32_t parent) {
    fbb_.AddElement<int32_t>(Transform::VT_PARENT, parent, 0);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Transform::VT_NAME, name);
  }
  void add_translation(const O3DS::Data::Translation *translation) {
    fbb_.AddStruct(Transform::VT_TRANSLATION, translation);
  }
  void add_rotation(const O3DS::Data::Rotation *rotation) {
    fbb_.AddStruct(Transform::VT_ROTATION, rotation);
  }
  void add_scale(const O3DS::Data::Scale *scale) {
    fbb_.AddStruct(Transform::VT_SCALE, scale);
  }
  void add_matrix(flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::Matrix *>> matrix) {
    fbb_.AddOffset(Transform::VT_MATRIX, matrix);
  }
  void add_components(flatbuffers::Offset<flatbuffers::Vector<int8_t>> components) {
    fbb_.AddOffset(Transform::VT_COMPONENTS, components);
  }
  explicit TransformBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Transform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Transform>(end);
    return o;
  }
};

inline flatbuffers::Offset<Transform> CreateTransform(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t parent = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    const O3DS::Data::Translation *translation = nullptr,
    const O3DS::Data::Rotation *rotation = nullptr,
    const O3DS::Data::Scale *scale = nullptr,
    flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::Matrix *>> matrix = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> components = 0) {
  TransformBuilder builder_(_fbb);
  builder_.add_components(components);
  builder_.add_matrix(matrix);
  builder_.add_scale(scale);
  builder_.add_rotation(rotation);
  builder_.add_translation(translation);
  builder_.add_name(name);
  builder_.add_parent(parent);
  return builder_.Finish();
}

inline flatbuffers::Offset<Transform> CreateTransformDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t parent = 0,
    const char *name = nullptr,
    const O3DS::Data::Translation *translation = nullptr,
    const O3DS::Data::Rotation *rotation = nullptr,
    const O3DS::Data::Scale *scale = nullptr,
    const std::vector<O3DS::Data::Matrix> *matrix = nullptr,
    const std::vector<int8_t> *components = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto matrix__ = matrix ? _fbb.CreateVectorOfStructs<O3DS::Data::Matrix>(*matrix) : 0;
  auto components__ = components ? _fbb.CreateVector<int8_t>(*components) : 0;
  return O3DS::Data::CreateTransform(
      _fbb,
      parent,
      name__,
      translation,
      rotation,
      scale,
      matrix__,
      components__);
}

struct Subject FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SubjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODES = 4,
    VT_NAME = 6,
    VT_X_AXIS = 8,
    VT_Y_AXIS = 10,
    VT_Z_AXIS = 12,
    VT_FORMAT = 14,
    VT_CURVES = 16
  };
  const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Transform>> *nodes() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Transform>> *>(VT_NODES);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  O3DS::Data::Direction x_axis() const {
    return static_cast<O3DS::Data::Direction>(GetField<int8_t>(VT_X_AXIS, 0));
  }
  O3DS::Data::Direction y_axis() const {
    return static_cast<O3DS::Data::Direction>(GetField<int8_t>(VT_Y_AXIS, 0));
  }
  O3DS::Data::Direction z_axis() const {
    return static_cast<O3DS::Data::Direction>(GetField<int8_t>(VT_Z_AXIS, 0));
  }
  const flatbuffers::String *format() const {
    return GetPointer<const flatbuffers::String *>(VT_FORMAT);
  }
  const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Curve>> *curves() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Curve>> *>(VT_CURVES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_X_AXIS, 1) &&
           VerifyField<int8_t>(verifier, VT_Y_AXIS, 1) &&
           VerifyField<int8_t>(verifier, VT_Z_AXIS, 1) &&
           VerifyOffset(verifier, VT_FORMAT) &&
           verifier.VerifyString(format()) &&
           VerifyOffset(verifier, VT_CURVES) &&
           verifier.VerifyVector(curves()) &&
           verifier.VerifyVectorOfTables(curves()) &&
           verifier.EndTable();
  }
};

struct SubjectBuilder {
  typedef Subject Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_nodes(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Transform>>> nodes) {
    fbb_.AddOffset(Subject::VT_NODES, nodes);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Subject::VT_NAME, name);
  }
  void add_x_axis(O3DS::Data::Direction x_axis) {
    fbb_.AddElement<int8_t>(Subject::VT_X_AXIS, static_cast<int8_t>(x_axis), 0);
  }
  void add_y_axis(O3DS::Data::Direction y_axis) {
    fbb_.AddElement<int8_t>(Subject::VT_Y_AXIS, static_cast<int8_t>(y_axis), 0);
  }
  void add_z_axis(O3DS::Data::Direction z_axis) {
    fbb_.AddElement<int8_t>(Subject::VT_Z_AXIS, static_cast<int8_t>(z_axis), 0);
  }
  void add_format(flatbuffers::Offset<flatbuffers::String> format) {
    fbb_.AddOffset(Subject::VT_FORMAT, format);
  }
  void add_curves(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Curve>>> curves) {
    fbb_.AddOffset(Subject::VT_CURVES, curves);
  }
  explicit SubjectBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Subject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Subject>(end);
    return o;
  }
};

inline flatbuffers::Offset<Subject> CreateSubject(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Transform>>> nodes = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    O3DS::Data::Direction x_axis = O3DS::Data::Direction_None,
    O3DS::Data::Direction y_axis = O3DS::Data::Direction_None,
    O3DS::Data::Direction z_axis = O3DS::Data::Direction_None,
    flatbuffers::Offset<flatbuffers::String> format = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Curve>>> curves = 0) {
  SubjectBuilder builder_(_fbb);
  builder_.add_curves(curves);
  builder_.add_format(format);
  builder_.add_name(name);
  builder_.add_nodes(nodes);
  builder_.add_z_axis(z_axis);
  builder_.add_y_axis(y_axis);
  builder_.add_x_axis(x_axis);
  return builder_.Finish();
}

inline flatbuffers::Offset<Subject> CreateSubjectDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<O3DS::Data::Transform>> *nodes = nullptr,
    const char *name = nullptr,
    O3DS::Data::Direction x_axis = O3DS::Data::Direction_None,
    O3DS::Data::Direction y_axis = O3DS::Data::Direction_None,
    O3DS::Data::Direction z_axis = O3DS::Data::Direction_None,
    const char *format = nullptr,
    const std::vector<flatbuffers::Offset<O3DS::Data::Curve>> *curves = nullptr) {
  auto nodes__ = nodes ? _fbb.CreateVector<flatbuffers::Offset<O3DS::Data::Transform>>(*nodes) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto format__ = format ? _fbb.CreateString(format) : 0;
  auto curves__ = curves ? _fbb.CreateVector<flatbuffers::Offset<O3DS::Data::Curve>>(*curves) : 0;
  return O3DS::Data::CreateSubject(
      _fbb,
      nodes__,
      name__,
      x_axis,
      y_axis,
      z_axis,
      format__,
      curves__);
}

struct SubjectUpdate FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SubjectUpdateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TRANSLATIONS = 6,
    VT_ROTATION = 8,
    VT_SCALE = 10,
    VT_CURVES = 12
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::Vector<const O3DS::Data::TranslationUpdate *> *translations() const {
    return GetPointer<const flatbuffers::Vector<const O3DS::Data::TranslationUpdate *> *>(VT_TRANSLATIONS);
  }
  const flatbuffers::Vector<const O3DS::Data::RotationUpdate *> *rotation() const {
    return GetPointer<const flatbuffers::Vector<const O3DS::Data::RotationUpdate *> *>(VT_ROTATION);
  }
  const flatbuffers::Vector<const O3DS::Data::ScaleUpdate *> *scale() const {
    return GetPointer<const flatbuffers::Vector<const O3DS::Data::ScaleUpdate *> *>(VT_SCALE);
  }
  const flatbuffers::Vector<const O3DS::Data::CurveUpdate *> *curves() const {
    return GetPointer<const flatbuffers::Vector<const O3DS::Data::CurveUpdate *> *>(VT_CURVES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TRANSLATIONS) &&
           verifier.VerifyVector(translations()) &&
           VerifyOffset(verifier, VT_ROTATION) &&
           verifier.VerifyVector(rotation()) &&
           VerifyOffset(verifier, VT_SCALE) &&
           verifier.VerifyVector(scale()) &&
           VerifyOffset(verifier, VT_CURVES) &&
           verifier.VerifyVector(curves()) &&
           verifier.EndTable();
  }
};

struct SubjectUpdateBuilder {
  typedef SubjectUpdate Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(SubjectUpdate::VT_NAME, name);
  }
  void add_translations(flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::TranslationUpdate *>> translations) {
    fbb_.AddOffset(SubjectUpdate::VT_TRANSLATIONS, translations);
  }
  void add_rotation(flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::RotationUpdate *>> rotation) {
    fbb_.AddOffset(SubjectUpdate::VT_ROTATION, rotation);
  }
  void add_scale(flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::ScaleUpdate *>> scale) {
    fbb_.AddOffset(SubjectUpdate::VT_SCALE, scale);
  }
  void add_curves(flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::CurveUpdate *>> curves) {
    fbb_.AddOffset(SubjectUpdate::VT_CURVES, curves);
  }
  explicit SubjectUpdateBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SubjectUpdate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SubjectUpdate>(end);
    return o;
  }
};

inline flatbuffers::Offset<SubjectUpdate> CreateSubjectUpdate(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::TranslationUpdate *>> translations = 0,
    flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::RotationUpdate *>> rotation = 0,
    flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::ScaleUpdate *>> scale = 0,
    flatbuffers::Offset<flatbuffers::Vector<const O3DS::Data::CurveUpdate *>> curves = 0) {
  SubjectUpdateBuilder builder_(_fbb);
  builder_.add_curves(curves);
  builder_.add_scale(scale);
  builder_.add_rotation(rotation);
  builder_.add_translations(translations);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<SubjectUpdate> CreateSubjectUpdateDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<O3DS::Data::TranslationUpdate> *translations = nullptr,
    const std::vector<O3DS::Data::RotationUpdate> *rotation = nullptr,
    const std::vector<O3DS::Data::ScaleUpdate> *scale = nullptr,
    const std::vector<O3DS::Data::CurveUpdate> *curves = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto translations__ = translations ? _fbb.CreateVectorOfStructs<O3DS::Data::TranslationUpdate>(*translations) : 0;
  auto rotation__ = rotation ? _fbb.CreateVectorOfStructs<O3DS::Data::RotationUpdate>(*rotation) : 0;
  auto scale__ = scale ? _fbb.CreateVectorOfStructs<O3DS::Data::ScaleUpdate>(*scale) : 0;
  auto curves__ = curves ? _fbb.CreateVectorOfStructs<O3DS::Data::CurveUpdate>(*curves) : 0;
  return O3DS::Data::CreateSubjectUpdate(
      _fbb,
      name__,
      translations__,
      rotation__,
      scale__,
      curves__);
}

struct SubjectList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SubjectListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBJECTS = 4,
    VT_UPDATES = 6,
    VT_TIME = 8
  };
  const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Subject>> *subjects() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Subject>> *>(VT_SUBJECTS);
  }
  const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::SubjectUpdate>> *updates() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::SubjectUpdate>> *>(VT_UPDATES);
  }
  double time() const {
    return GetField<double>(VT_TIME, 0.0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SUBJECTS) &&
           verifier.VerifyVector(subjects()) &&
           verifier.VerifyVectorOfTables(subjects()) &&
           VerifyOffset(verifier, VT_UPDATES) &&
           verifier.VerifyVector(updates()) &&
           verifier.VerifyVectorOfTables(updates()) &&
           VerifyField<double>(verifier, VT_TIME, 8) &&
           verifier.EndTable();
  }
};

struct SubjectListBuilder {
  typedef SubjectList Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_subjects(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Subject>>> subjects) {
    fbb_.AddOffset(SubjectList::VT_SUBJECTS, subjects);
  }
  void add_updates(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::SubjectUpdate>>> updates) {
    fbb_.AddOffset(SubjectList::VT_UPDATES, updates);
  }
  void add_time(double time) {
    fbb_.AddElement<double>(SubjectList::VT_TIME, time, 0.0);
  }
  explicit SubjectListBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<SubjectList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SubjectList>(end);
    return o;
  }
};

inline flatbuffers::Offset<SubjectList> CreateSubjectList(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::Subject>>> subjects = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<O3DS::Data::SubjectUpdate>>> updates = 0,
    double time = 0.0) {
  SubjectListBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_updates(updates);
  builder_.add_subjects(subjects);
  return builder_.Finish();
}

inline flatbuffers::Offset<SubjectList> CreateSubjectListDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<O3DS::Data::Subject>> *subjects = nullptr,
    const std::vector<flatbuffers::Offset<O3DS::Data::SubjectUpdate>> *updates = nullptr,
    double time = 0.0) {
  auto subjects__ = subjects ? _fbb.CreateVector<flatbuffers::Offset<O3DS::Data::Subject>>(*subjects) : 0;
  auto updates__ = updates ? _fbb.CreateVector<flatbuffers::Offset<O3DS::Data::SubjectUpdate>>(*updates) : 0;
  return O3DS::Data::CreateSubjectList(
      _fbb,
      subjects__,
      updates__,
      time);
}

struct Curve FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CurveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALUE = 6
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct CurveBuilder {
  typedef Curve Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Curve::VT_NAME, name);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(Curve::VT_VALUE, value, 0.0f);
  }
  explicit CurveBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Curve> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Curve>(end);
    return o;
  }
};

inline flatbuffers::Offset<Curve> CreateCurve(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    float value = 0.0f) {
  CurveBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<Curve> CreateCurveDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    float value = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return O3DS::Data::CreateCurve(
      _fbb,
      name__,
      value);
}

inline const O3DS::Data::SubjectList *GetSubjectList(const void *buf) {
  return flatbuffers::GetRoot<O3DS::Data::SubjectList>(buf);
}

inline const O3DS::Data::SubjectList *GetSizePrefixedSubjectList(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<O3DS::Data::SubjectList>(buf);
}

inline bool VerifySubjectListBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<O3DS::Data::SubjectList>(nullptr);
}

inline bool VerifySizePrefixedSubjectListBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<O3DS::Data::SubjectList>(nullptr);
}

inline void FinishSubjectListBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<O3DS::Data::SubjectList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSubjectListBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<O3DS::Data::SubjectList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Data
}  // namespace O3DS

#endif  // FLATBUFFERS_GENERATED_O3DS_O3DS_DATA_H_
